//
//  BehavioursStyleKit.h
//  PencilCase
//
//  Created by Cody Rayment on 2014-12-03.
//  Copyright (c) 2014 Robots & Pencils. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface BehavioursStyleKit : NSObject

+ (NSColor *)lightBlueColor;
+ (NSColor *)normalBlueColor;
+ (NSColor *)darkBlueColor;
+ (NSColor *)errorColor;

// Drawing Methods
+ (void)drawThenWithFrame: (NSRect)frame sourceHighlightColor: (NSColor*)sourceHighlightColor topConnected: (BOOL)topConnected bottomConnected: (BOOL)bottomConnected isSelected: (BOOL)isSelected isNextThenSelected: (BOOL)isNextThenSelected isSourceHighlighted: (BOOL)isSourceHighlighted hideTopConnector: (BOOL)hideTopConnector hideBottomConnector: (BOOL)hideBottomConnector;
+ (void)drawConnectorWithSourceHighlightColor: (NSColor*)sourceHighlightColor bottomConnected: (BOOL)bottomConnected isSelected: (BOOL)isSelected isSourceHighlighted: (BOOL)isSourceHighlighted;
+ (void)drawAddThenWithFrame: (NSRect)frame;
+ (void)drawTokenBackgroundWithFrame: (NSRect)frame sourceHighlight: (BOOL)sourceHighlight rightConnected: (BOOL)rightConnected leftConnected: (BOOL)leftConnected insertNewMode: (BOOL)insertNewMode invalidToken: (BOOL)invalidToken;

@end
