source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:RobotsAndPencils/RNPPrivateSpecs.git'

workspace '../PencilCaseLauncherDemo'
platform :ios, '8.0'

inhibit_all_warnings!

target 'PencilCaseLauncherDemo' do
    pod 'PencilCaseLauncher', :path => '../../'
end

target 'PencilCaseLauncherDemoTests' do
    pod 'Kiwi'
    pod 'OHHTTPStubs'
end